title: Spencer Fielding # your name (or website title) here
logo: "/images/Profile_Picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a master's student at the University of Oklahoma in geospatial technologies. Below are some of the projects that I have worked on.
  This is a work in progress and will be updated with new and exciting items as time goes on. 
  <br><br>
  <a href="https://www.linkedin.com/in/spencer-fielding/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
